---
- block:
    - name: Set Gnome Settings
      ansible.builtin.shell: "gsettings set {{ item }}"
      loop:
        # - "org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 42"
        # - "org.gnome.shell.extensions.dash-to-dock dock-fixed false"
        # - "org.gnome.desktop.interface icon-theme 'Yaru'"
        # - "org.gnome.desktop.interface cursor-theme 'Yaru'"
        - "org.gnome.desktop.wm.preferences button-layout ':close'"
        - "org.gnome.desktop.interface show-battery-percentage true"
      when: "ansible_distribution == 'fedora'"

    - name: "MacOS Dock Config"
      ansible.builtin.shell: "{{ item }}"
      args:
        chdir: "{{ cmd_home }}"
      loop:
        - "defaults write com.apple.dock autohide-delay -float 1000; killall Dock"
        - "defaults write com.apple.dock persistent-apps -array; killall Dock"
      when: "ansible_distribution == 'MacOSX'"

    - name: Configuring user shell
      ansible.builtin.shell: "chsh -s /usr/bin/zsh {{ cmd_user }}"
      become: true

    - name: Installing pip dependencies
      ansible.builtin.pip:
        name: "{{ item }}"
        extra_args: "--user --no-warn-script-location --no-cache-dir --upgrade --break-system-packages"
      loop:
        - pip
        - jmespath
        - pynvim
        - uv

    - name: Finalizing the installation
      ansible.builtin.shell: "{{ item }}"
      args:
        chdir: "{{ cmd_home }}"
      loop:
        - bash -c "zsh <(curl --proto '=https' --tlsv1.2 -LsSf 'https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh') --branch release-v1"
        - rm .profile .bashrc .bash_logout .zshrc || true
        - if [ ! -d "{{ cmd_home }}/.config" ]; then mkdir .config; fi;
        - stow -d .dotfiles -t "${HOME}" .
        - "/usr/bin/nvim --headless -c 'qall' || true"
        - bash -c "zsh -c 'rm -rf ~/.local/share/zap/plugins/* && source ~/.zshrc && zap update all'"

  vars:
    cmd_home: "{{ lookup('env','HOME') }}"
    cmd_user: "{{ lookup('env', 'USER') }}"
