#!/usr/bin/env bash

LOG_FILE="/tmp/bootstrap_log.txt"
exec > >(tee -a "$LOG_FILE") 2>&1

set -e

# Color Definitions
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "\n${GREEN}Log file created at: ${LOG_FILE}${NC}"

export HISTIGNORE='*sudo -S*'

# Print colored header
echo -e "\n${BLUE}-----------------------------------${NC}"
echo -e "${GREEN}Bootstrapping your system${NC}"
echo -e "${BLUE}-----------------------------------${NC}\n"

# Detecting the operating system
OSTYPE=$(uname -s | tr '[:upper:]' '[:lower:]')
if [[ "$OSTYPE" == "linux"* ]]; then
  DIST=$(awk -F= '$1=="ID" { print $2 ;}' /etc/os-release)
fi

echo -e "${YELLOW}OSTYPE:${NC} ${OSTYPE}"
echo -e "${YELLOW}DIST  :${NC} ${DIST}"
echo -e "${BLUE}-----------------------------------${NC}"

# Function to handle errors
handle_error() {
    echo -e "${RED}An error occurred. Please check the log for details.${NC}"
    exit 1
}
trap handle_error ERR

# Validate Sudo Access
echo -e "\n${YELLOW}Please enter your sudo password (for installing base packages and Ansible privileges):${NC}"
read -s -p "Password: " SUDO_PASSWORD
echo -e '\n'
echo "${SUDO_PASSWORD}" | sudo -S -v &>/dev/null
if [[ $? -ne 0 ]]; then
    echo -e "${RED}Error: Invalid sudo password or no sudo privileges.${NC}"
    exit 1
fi

# Check for Internet Connection
check_internet_connection() {
    echo -e "${BLUE}-----------------------------------${NC}"
    echo -e "${GREEN}Checking Internet Connection${NC}"
    echo -e "${BLUE}-----------------------------------${NC}"

    if ping -c 1 google.com &>/dev/null; then
        echo -e "${GREEN}Internet connection is available.${NC}"
    else
        echo -e "${RED}No internet connection detected. Please check your network.${NC}"
        exit 1
    fi
}

check_internet_connection

# Backup function for important files
backup_file() {
    local FILE=$1
    if [[ -f "$FILE" ]]; then
        echo -e "${YELLOW}Backing up ${FILE} to ${FILE}.bak${NC}"
        echo "${SUDO_PASSWORD}" | sudo -S -k cp "$FILE" "${FILE}.bak"
    fi
}

install_homebrew() {
    echo -e "${BLUE}-----------------------------------${NC}"
    echo -e "${GREEN}Installing Homebrew${NC}"
    echo -e "${BLUE}-----------------------------------${NC}"
    if ! command -v brew &>/dev/null; then
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    else
        echo -e "${YELLOW}Homebrew is already installed${NC}"
    fi
}

install_linux_deps(){
  commonPkgs="python3-pip stow git make gnome-network-displays"

  case "$DIST" in
    debian|ubuntu)
        targetPkgs="python3-minimal python3-venv locales"
        echo "${SUDO_PASSWORD}" | sudo -S apt-get update -y
        echo "${SUDO_PASSWORD}" | sudo -S apt-get upgrade -y
        echo "${SUDO_PASSWORD}" | sudo -S apt-get install --no-install-recommends -y $commonPkgs $targetPkgs
        ;;
    fedora)
        targetPkgs="neovim python3-neovim alacritty"
        echo "${SUDO_PASSWORD}" | sudo -S dnf update -y
        echo "${SUDO_PASSWORD}" | sudo -S dnf install -y --skip-unavailable $commonPkgs $targetPkgs
        ;;
    *)
        echo -e "${RED}No task defined for $DIST on Linux${NC}"
        exit 1
        ;;
  esac
}

# Install dependencies based on OS type
case "$OSTYPE" in
    darwin*)
        install_homebrew
        eval "$(/opt/homebrew/bin/brew shellenv)"
        ;;
    linux*)
        install_linux_deps
        install_homebrew
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        if [ $? -eq 0 ]; then
          echo "${SUDO_PASSWORD}" | echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' | sudo -S tee -a /root/.bash_profile > /dev/null
        fi
        ;;
    *)
        echo -e "${RED}Unsupported OS${NC}"
        exit 1
        ;;
esac

# Install Python dependencies
echo -e "${BLUE}-----------------------------------${NC}"
echo -e "${GREEN}Installing Python3 Dependencies${NC}"
echo -e "${BLUE}-----------------------------------${NC}"
pip3 install --upgrade --no-cache-dir --break-system-packages pip ansible --no-warn-script-location

# Clone or update dotfiles
DOTFILES_DIR="${HOME}/.dotfiles"
if [[ ! -d "$DOTFILES_DIR" ]]; then
    echo -e "${GREEN}Cloning psadi/.dotfiles${NC}"
    git clone https://github.com/psadi/dotfiles.git "$DOTFILES_DIR"
else
    echo -e "${YELLOW}psadi/.dotfiles already exists, pulling latest changes${NC}"
    cd "$DOTFILES_DIR" && git pull && cd -
fi

# Export required variables for Ansible
export PATH="${HOME}/.local/bin:$PATH"
export ANSIBLE_CONFIG="${HOME}/.dotfiles/ansible/ansible.cfg"
export ANSIBLE_INVENTORY_WARNING=false
export ANSIBLE_BECOME_PASSWORD="${SUDO_PASSWORD}"

# Dynamic tag support for Ansible playbook
TAGS="${1:-$OSTYPE}" # Use first argument or fallback to OSTYPE
echo -e "${BLUE}Running Ansible Playbook with tags: ${TAGS}${NC}"
ansible-playbook "${DOTFILES_DIR}/ansible/site.yaml" --tags "$TAGS" --user "$USER"

exit $?

