---
apt_packages_0:
  - build-essential
  - curl
  - fonts-powerline
  - git
  - jq
  - locales
  - man
  - procps
  - stow
  - unzip
  - zip
  - zsh

apt_packages_1:
  - gnome-tweaks
  - mpv
  - powertop
  - preload
  - qpdf
  - smartmontools
  - wl-clipboard
  - xsel

ubuntu_deb_packages:
  libssl1.1:
    version: 1_1.1.1f-1ubuntu2.23
    url: http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.%version%_amd64.deb
  wezterm:
    version: 20240203-110809-5046fc22
    url: https://github.com/wez/wezterm/releases/download/%version%/wezterm-%version%.Ubuntu20.04.deb
  minecraft-launcher:
    version:
    url: https://launcher.mojang.com/download/Minecraft.deb

ubuntu_snap_packages:
  - discord
  - docker
  - firefox
  - gimp
  - onlyoffice-desktopeditors
  - shotcut
  - thunderbird
  - vlc
