---
apt_packages_0:
  - build-essential
  - git
  - curl
  - zsh
  - jq
  - zip
  - unzip
  - stow
  - locales
  - man
  - fonts-powerline
  - procps

apt_packages_1:
  - tlp
  - powertop
  - preload
  - xclip
  - smartmontools
  # - foot

ubuntu_deb_packages:
  # libssl1.1:
  #   version: 1_1.1.1f-1ubuntu2.23
  #   url: http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.%version%_amd64.deb
  # wezterm:
  #   version: 20240203-110809-5046fc22
  #   url: https://github.com/wez/wezterm/releases/download/%version%/wezterm-%version%.Ubuntu20.04.deb
  # docker-ce-cli:
  #   version: 27.3.1-1
  #   url: https://download.docker.com/linux/ubuntu/dists/noble/pool/stable/amd64/docker-ce-cli_%version%~ubuntu.24.04~noble_amd64.deb
  # google-chrome-stable:
  #   version:
  #   url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  # minecraft-launcher:
  #   version:
  #   url: https://launcher.mojang.com/download/Minecraft.deb
  # discord:
  #   version: 0.0.71
  #   url: https://stable.dl2.discordapp.net/apps/linux/%version%/discord-%version%.deb
  # zettlr:
  #   version: 3.2.2
  #   url: https://github.com/Zettlr/Zettlr/releases/download/v%version%/Zettlr-%version%-amd64.deb
