# vim:ft=config

font_family                     GeistMono Nerd Font
bold_font                       auto
italic_font                     auto
bold_italic_font                auto
font_size                       16.0
font_features                   GeistMono-Nerd-Font -liga -calt

copy_on_select                  yes

cursor_trail                    1
cursor_trail_decay              0.1 0.4
cursor_trail_start_threshold    2

draw_minimal_borders            yes
hide_window_decorations         yes
sync_to_monitor                 yes

tab_bar_edge                    top
tab_bar_min_tabs                1
tab_bar_style                   separator
tab_separator                    " | "
tab_title_max_length            10
tab_title_template              "{index}:{tab.active_exe}"

underline_hyperlinks            always

window_margin_width             0
window_padding_width            0

# Keybindings

map ctrl+t          new_tab
map ctrl+]          next_tab
map ctrl+[          previous_tab
map ctrl+enter      toggle_fullscreen
map ctrl+shift+]    move_tab_forward
map ctrl+shift+[    move_tab_backward


include kangawa-kitty.conf
