# -*- conf -*-

font=MonoLisa Nerd Font:size=16
initial-window-mode=maximized

[scrollback]
lines=10000
multiplier=3.0

[mouse]
hide-when-typing=yes
alternate-scroll-mode=yes

[cursor]
color=191724 e0def4
style=underline
blink=yes

[colors]
background=191724
foreground=e0def4
regular0=26233a
regular1=eb6f92
regular2=9ccfd8
regular3=f6c177
regular4=31748f
regular5=c4a7e7
regular6=ebbcba
regular7=e0def4

bright0=6e6a86
bright1=eb6f92
bright2=9ccfd8
bright3=f6c177
bright4=31748f
bright5=c4a7e7
bright6=ebbcba
bright7=e0def4

[csd]
preferred=none
hide-when-maximized=yes

[url-bindings]
cancel=Control+g Control+c Control+d Escape
toggle-url-visible=t

[url]
launch=xdg-open ${url}
label-letters=sadfjklewcmpgh
osc8-underline=url-mode
protocols=http, https, ftp, ftps, file, gemini, gopher
uri-characters=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_.,~:;/?#@!$&%*+="'()[]


[search-bindings]
cursor-left=Left Control+b
cursor-left-word=Mod1+Left
cursor-right=Right Control+f
cursor-right-word=Mod1+Right
cursor-home=Home Control+a
cursor-end=End Control+e
delete-prev=BackSpace
delete-prev-word=Mod1+BackSpace
delete-next=Delete
delete-next-word=Mod1+Shift+BackSpace
clipboard-paste=Control+v Control+Shift+v XF86Paste
primary-paste=Shift+Insert
