---
- set_fact:
    url: "{{ pkg.value[os] | regex_replace('%version%', version) }}"

- set_fact:
    basepath: "{{ url.split('/')[-1] | regex_replace('\\.(tar(\\.gz|\\.xz|\\.bz2|\\.lzma|\\.lz4|\\.zst)?|tgz|zip)$', '') }}"

- ansible.builtin.stat:
    path: "/opt/pkg/{{ basepath }}"
  register: basepath_exists

- ansible.builtin.stat:
    path: "/opt/pkg/{{ pkg.key }}"
  register: key_exists

- block:
    - debug:
        msg: "Installing package {{ pkg.key }} version {{ pkg.value.version }}"

    - name: Ensure destination directory exists
      file:
        path: "/opt/pkg"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
      become: true

    - name: "Downloading '{{ url }}' package"
      get_url:
        url: "{{ url }}"
        dest: "/tmp"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: 0755

    - name: "Extracting '{{ url.split('/')[-1] }}' package"
      unarchive:
        src: "/tmp/{{ url.split('/')[-1] }}"
        dest: "/opt/pkg"
        mode: 0755
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        remote_src: true

    - name: Cleaning up
      file:
        path: "/tmp/{{ url.split('/')[-1] }}"
        state: absent

  when: basepath_exists.stat.exists == false and not key_exists.stat.exists
