- name: Personal Development Environment
  hosts: localhost
  gather_facts: true
  any_errors_fatal: true
  vars:
    ansible_become_password: '{{ lookup("env", "ANSIBLE_BECOME_PASSWORD") }}'
  roles:
    - role: apt
      tags: linux

    - role: github
      tags: linux

    - role: homebrew
      tags: darwin

    - role: opt
      tags:
        - linux
        - darwin

    - role: cmd
      tags:
        - linux
        - darwin

    - role: macos
      tags: darwin

    - role: pip
      tags:
        - linux
        - darwin
