---
flatpak_packages_id:
  - com.discordapp.Discord
  - com.mattjakeman.ExtensionManager
  - com.obsproject.Studio
  - eu.betterbird.Betterbird
  - org.gimp.GIMP
  - org.shotcut.Shotcut
  - org.videolan.VLC
  - org.wezfurlong.wezterm
