---
- name: Update cache & all Packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Upgrade all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
  become: true

- name: get the apt package facts
  package_facts:
    manager: "apt"

- set_fact:
    is_gui: "{{ ansible_facts.packages['ubuntu-desktop-minimal'] is defined }}"

- name: Installing apt dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ apt_packages_0 }}"
  become: true
  when: item not in ansible_facts.packages.keys()

- block:
    - name: Installing apt dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop: "{{ apt_packages_1 }}"
      become: true

    - name: Remove "{{ item }}" package
      ansible.builtin.apt:
        name: "{{ item }}"
        state: absent
      loop: "{{ apt_purge_packages }}"
      when: ((apt_purge_packages is defined) and (apt_purge_packages | length > 0))
  when: is_gui and not in_docker and item not in ansible_facts.packages.keys()

- name: Clean apt cache
  ansible.builtin.apt:
    autoclean: true
  become: true
  when: in_docker

- name: Remove unused packages
  ansible.builtin.apt:
    autoremove: true
    purge: true
  become: true

- block:
    - include_tasks: deb.yaml
      vars:
        version: "{{ pkg.value.version }}"
      loop_control:
        loop_var: pkg
      loop: "{{ ubuntu_deb_packages | dict2items }}"
      when: pkg.key not in ansible_facts.packages.keys()

    - name: Installing Snap Packages
      community.general.snap:
        name: "{{ item.name }}"
        classic: "{{ item.classic }}"
      become: true
      loop: "{{ ubuntu_snap_packages }}"
  when: is_gui and not in_docker
