#!/bin/sh

########################################################
#                      _ _
#  _ __  ___  __ _  __| (_)
# | '_ \/ __|/ _` |/ _` | |
# | |_) \__ \ (_| | (_| | |
# | .__/|___/\__,_|\__,_|_|
# |_|
## Name   : P S, Adithya
## email  : adithya3494@gmail.com
## gitlab : https://github.com/psadi
########################################################


export OSTYPE="$(uname -a | awk '{print $1}')"
ZSH_DOTFILES_DIR="${HOME}/Developer/dotfiles/zsh"

source "${ZSH_DOTFILES_DIR}/${OSTYPE}.zshrc"
source "${ZSH_DOTFILES_DIR}/_zsh.zsh"