---
- set_fact:
    package_name: "{% if 'binary' in package %}{{ package.binary }}{% else %}{{ package.name.split('/')[-1] }}{% endif %}"

- name: Check if '{{ package_name }}' exists
  stat:
    path: "{{ package.destination }}/{{ package_name }}"
  register: st

- block:
    - debug:
        msg: "Installing '{{ package.name }}'..."

    - name: Fetch latest github release
      uri:
        url: "https://api.github.com/repos/{{ package.name }}/releases/latest"
        return_content: yes
        status_code: 200
      failed_when: github_release.status != 200
      register: github_release

    - set_fact:
        _url: "{% if package.replace_version %}{{ package.url | regex_replace('\\[VERSION\\]', github_release.json.tag_name  | regex_replace('v', '')) }}{% else %}{{ package.url | regex_replace('\\[VERSION\\]', github_release.json.tag_name ) }}{% endif %}"
        _extra_opts: "{{ package.extra_opts | regex_replace('\\[VERSION\\]', github_release.json.tag_name ) }}"

    - name: "Downloading '{{ _url }}' package"
      get_url:
        url: "{{ _url }}"
        dest: "/tmp"
        mode: 0755
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"

    - name: Ensure destination directory exists
      file:
        path: "{{ package.destination }}"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
      become: true

    - name: "Extracting '{{ _url.split('/')[-1] }}' package"
      unarchive:
        src: "/tmp/{{ _url.split('/')[-1] }}"
        dest: "{{ package.destination }}"
        mode: 0755
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        extra_opts: "{{ _extra_opts }}"
        remote_src: true
      when: "'.zip' not in _url.split('/')[-1]"

    - name: "Extracting '{{ _url.split('/')[-1] }}' package"
      command: "unzip -oqj /tmp/{{ _url.split('/')[-1] }} {{ _extra_opts }} -d {{ package.destination }}"
      when: "'.zip' in _url.split('/')[-1]"

    - name: Cleaning up
      file:
        path: "/tmp/{{ _url.split('/')[-1] }}"
        state: absent

  always:
    - set_fact:
        _url: null
        package_name: null

  when: "st.stat.path is undefined"
