[general]
live_config_reload = true
# import = ["~/.config/alacritty/colors/tokyonight_night.toml"]

[font]
normal = { family = "Maple Mono NF", style = "Regular" }
bold = { family = "Maple Mono NF", style = "Bold" }
italic = { family = "Maple Mono NF", style = "Italic" }
size = 16

[window]
startup_mode = "Maximized"
title = "~"
dynamic_title = true

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Underline", blinking = "On" }

[keyboard]
bindings = [
  {chars = "\u001Bb", key = "Left", mods = "Alt"},
  {chars = "\u001Bf", key = "Right", mods = "Alt"},
  {chars = "\u001b\u007f", key = "Backspace", mods = "Alt"},
]
