[general]
import = ["~/.config/alacritty/colors/tokyonight_night.toml"]
live_config_reload = true

[font]
bold = { family = "MonoLisa Nerd Font", style = "Bold" }
italic = { family = "MonoLisa Nerd Font", style = "Italic" }
normal = { family = "MonoLisa Nerd Font", style = "Regular" }
size = 16

[window]
decorations_theme_variant = "Dark"
dynamic_title = false
startup_mode = "Maximized"
title = "~"

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Underline", blinking = "On" }

[keyboard]
bindings = [
  {chars = "\u001Bb", key = "Left", mods = "Alt"},
  {chars = "\u001Bf", key = "Right", mods = "Alt"},
  {chars = "\u001b\u007f", key = "Backspace", mods = "Alt"},
]
