[tools]
go = "latest"
lua-language-server = "latest"
terraform = "latest"
terraform-ls = "latest"
ty = "latest"
uv = "latest"
ruff = "latest"
lazygit = "latest"
helm = "latest"
kubectl = "latest"
yazi = "latest"
bun = "latest"
node = "22"
