[tools]
go = "latest"
lua-language-server = "latest"
node = "latest"
opencode = "latest"
terraform = "latest"
terraform-ls = "latest"
ty = "latest"
uv = "latest"
ruff = "latest"
lazygit = "latest"
upx = "latest"
pre-commit = "latest"
delta = "latest"
codex = "latest"
bat = "latest"
bottom = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
gh = "latest"
helm = "latest"
hyperfine = "latest"
jq = "latest"
kubectl = "latest"
ripgrep = "latest"
yazi = "latest"
zoxide = "latest"
fzf = "latest"
